# Data representations for neural networks
- nd-Array = tensor
- count number of opening brackets [[[==number dimension, rank,axis

# 2.2.1 Scalars (0D tensors)

In [1]:
import numpy as np

a = np.array(12)
a
a.ndim

0

# 2.2.2 Vectors (1D tensors)

In [2]:
a = np.array([1,3,4,9])

print(a)
print("Dimension", a.ndim)
print("Shape", a.shape)

# 1D Tensor, 1 Rank Tensor, Vector, 1Axes Tensor

[1 3 4 9]
Dimension 1
Shape (4,)


# 2.2.3 Matrices (2D tensors)

In [3]:
a = np.array([[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]])

print(a)
print("Dimension", a.ndim)
print("Shape", a.shape)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
Dimension 2
Shape (3, 5)


# 2.2.4 3D tensors and higher-dimensional tensors

In [4]:
a = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])

print(a)
print("Dimension", a.ndim)
print("Shape", a.shape)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
Dimension 3
Shape (3, 3, 5)


In [5]:
a = np.ones((2,2,2,2,2))

print(a)
print("Dimension", a.ndim)
print("Shape", a.shape)

[[[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]



 [[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]]
Dimension 5
Shape (2, 2, 2, 2, 2)


# 2.2.5 Key attributes
- Number Of Axis
- Shape
- Data Type(Usually called dtype in Python Libraries)

# 2.2.6 Manipulating tensors in Numpy

In [6]:
my_slice = train_images[10:100]
print(my_slice.shape)

NameError: name 'train_images' is not defined