# Navy Code Functions

In [2]:
import numpy as np

In [5]:
a = np.random.randn(12).reshape((3,4))
a

array([[-0.8173628 ,  1.51590952,  2.05308776,  0.99399143],
       [-1.63696957, -1.75673462, -0.126695  , -0.7627096 ],
       [-0.89265948,  0.61408681, -1.38842026,  1.84279689]])

In [6]:
a + 2

array([[1.1826372 , 3.51590952, 4.05308776, 2.99399143],
       [0.36303043, 0.24326538, 1.873305  , 1.2372904 ],
       [1.10734052, 2.61408681, 0.61157974, 3.84279689]])

In [9]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x
naive_relu(a)

array([[0.        , 1.51590952, 2.05308776, 0.99399143],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.61408681, 0.        , 1.84279689]])

In [14]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x
naive_add(a, a+2)

array([[ 0.3652744 ,  5.03181904,  6.10617552,  3.98798287],
       [-1.27393913, -1.51346923,  1.74661001,  0.47458081],
       [ 0.21468104,  3.22817361, -0.77684052,  5.68559379]])

In [17]:
a = np.arange(32*10).reshape((32,10))
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [27]:
b = np.arange(10).reshape((1,10))
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
print(a.shape)
print(b.shape)

(32, 10)
(1, 10)


In [29]:
a + (b + 5)

array([[  5,   7,   9,  11,  13,  15,  17,  19,  21,  23],
       [ 15,  17,  19,  21,  23,  25,  27,  29,  31,  33],
       [ 25,  27,  29,  31,  33,  35,  37,  39,  41,  43],
       [ 35,  37,  39,  41,  43,  45,  47,  49,  51,  53],
       [ 45,  47,  49,  51,  53,  55,  57,  59,  61,  63],
       [ 55,  57,  59,  61,  63,  65,  67,  69,  71,  73],
       [ 65,  67,  69,  71,  73,  75,  77,  79,  81,  83],
       [ 75,  77,  79,  81,  83,  85,  87,  89,  91,  93],
       [ 85,  87,  89,  91,  93,  95,  97,  99, 101, 103],
       [ 95,  97,  99, 101, 103, 105, 107, 109, 111, 113],
       [105, 107, 109, 111, 113, 115, 117, 119, 121, 123],
       [115, 117, 119, 121, 123, 125, 127, 129, 131, 133],
       [125, 127, 129, 131, 133, 135, 137, 139, 141, 143],
       [135, 137, 139, 141, 143, 145, 147, 149, 151, 153],
       [145, 147, 149, 151, 153, 155, 157, 159, 161, 163],
       [155, 157, 159, 161, 163, 165, 167, 169, 171, 173],
       [165, 167, 169, 171, 173, 175, 177, 179, 181, 183